// Writes the island's GLSL modules from the approved prototype, pinned at v9.10 (tests/fixtures/hero-v9.10/template.html,
// read through tests/unit/proto-source.ts), byte for byte
// (hero-architecture.md 5.1: "GLSL strings are copied byte for byte"). Each literal keeps its raw source text; the slots
// that the v10 intro and section 2 plug into (architecture 11.1 and 11.2) are spliced in as interpolations that are
// empty by default, so every default string equals the prototype's. tests/unit/glsl.test.ts checks that on every run.
//   node scripts/hero/gen-glsl.mjs
import { writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { prototypeShaders } from '../../tests/unit/proto-source.ts';

const S = prototypeShaders();
const target = (rel) => fileURLToPath(new URL('../../src/scripts/hero/' + rel, import.meta.url));

/** Splices `${expr}` into a raw template literal right after the one occurrence of `after`. */
function slot(raw, after, expr) {
  if (raw[0] !== '`') throw new Error('slots need a template literal');
  const i = raw.indexOf(after);
  if (i < 0 || raw.indexOf(after, i + 1) >= 0) throw new Error('slot anchor must occur exactly once: ' + after);
  const at = i + after.length;
  return raw.slice(0, at) + '${' + expr + '}' + raw.slice(at);
}
const HEAD = (what) => `// Generated by scripts/hero/gen-glsl.mjs from prototype v9.10 (tests/fixtures/hero-v9.10/template.html; ${what}). Do not edit by hand:\n`
  + `// tests/unit/glsl.test.ts checks every default string against the prototype. Slots are empty by default.\n`;

// ---- logo (template.html lines 414 to 533)
const logo = HEAD('the logo material') + `
/** Insertion points for the v10 intro and section 2's logo morph (architecture 11.1, 11.2). */
export interface LogoSlots { vertPars?: string; vertPos?: string; fragPars?: string; fragOut?: string }

export const logoVert = (MAXB: number, s: LogoSlots = {}): string => ${slot(slot(S.logoVert, 'varying float vEdge;', "s.vertPars ?? ''"), 'qrot(uQ[i], local);', "s.vertPos ?? ''")};

export const logoFrag = (MAXB: number, s: LogoSlots = {}): string => ${slot(slot(S.logoFrag, 'varying float vEdge;', "s.fragPars ?? ''"), 'gl_FragColor = vec4(col, vSide > 0.5 ? 1.0 : 0.0);', "s.fragOut ?? ''")};
`;
writeFileSync(target('logo/shaders.ts'), logo);

// ---- world: sky (557 to 592), ground (620 to 676), wind bake (712 to 768), fog cards (779 to 874)
const world = HEAD('the sky dome, the ground patches, the wind bake and the fog cards') + `
/** Insertion points on the sky for the v10 intro (uFlat, uSkyP, uSkyB; architecture 11.1). */
export interface SkySlots { fragPars?: string; fragOut?: string }

export const SKY_VERT = ${S.skyVert};

export const skyFrag = (s: SkySlots = {}): string => ${slot(slot(S.skyFrag, 'varying vec2 vUv; varying vec3 vDir;', "s.fragPars ?? ''"), 'gl_FragColor = vec4(sky + wash * uHue * dark, 1.0);', "s.fragOut ?? ''")};

/** The ground's onBeforeCompile replacements: '#include <common>' and '#include <project_vertex>' in the vertex shader. */
export const GROUND_VERT_COMMON = ${S.groundVertCommon};
export const GROUND_VERT_PROJECT = ${S.groundVertProject};
/** The ground's fragment replacements: '#include <common>' (tone, crumb and mist declarations) and '#include <map_fragment>'. */
export const GROUND_FRAG_COMMON = ${S.groundFragCommon};
export const GROUND_FRAG_MAP = ${S.groundFragMap};

export const WIND_VERT = ${S.windVert};
export const WIND_FRAG = ${S.windFrag};

export const FOG_VERT = ${S.fogVert};
export const FOG_FRAG = ${S.fogFrag};
`;
writeFileSync(target('world/shaders.ts'), world);

// ---- post: the bloom restore pass (931 to 935) and the composite (991 to 1035)
const post = HEAD('the bloom restore pass and the wipe composite') + `
/** Insertion points on the composite for the v10 intro (uIntro) and section 2's rock modes (architecture 11.1, 11.2). */
export interface CompositeSlots { fragPars?: string; fragOut?: string }

export const RESTORE_VERT = ${S.restoreVert};
export const RESTORE_FRAG = ${S.restoreFrag};

export const COMPOSITE_VERT = ${S.compositeVert};

export const compositeFrag = (s: CompositeSlots = {}): string => ${slot(slot(S.compositeFrag, 'uniform vec2 uNoiseOff;', "s.fragPars ?? ''"), 'gl_FragColor = vec4(clamp(mix(s1, s2, cut), 0.0, 1.0), 1.0);', "s.fragOut ?? ''")};
`;
writeFileSync(target('post/shaders.ts'), post);
console.log('gen-glsl: wrote logo/shaders.ts, world/shaders.ts, post/shaders.ts');
