// Generates the shade data the site uses, from docs/data/shades-240.json (hero-architecture.md 6.1, hero spec D30):
//   src/styles/shades.gen.css  --shade-<id> for all 240 shades on :root, catalog order
//   src/config/shades.gen.ts   the 240 shades and the hero's selections (block glows, galaxy wash, glitch pairs), by id
//   src/data/family-keys.json  one key shade per family in catalog order (the hero's REGION), shared with section 2
//                              and the family pages (docs/specs/family-page.md 2.1)
// Everything is keyed by id: names repeat across families (Pastel six times, Neon four, Wine twice).
// Usage: node scripts/hero/gen-shades.mjs [--check]   (--check fails if a generated file is out of date)
import { readFileSync, writeFileSync, mkdirSync, existsSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = resolve(fileURLToPath(new URL('../..', import.meta.url)));
const SRC = join(ROOT, 'docs/data/shades-240.json');
const OUT_CSS = join(ROOT, 'src/styles/shades.gen.css');
const OUT_TS = join(ROOT, 'src/config/shades.gen.ts');
const OUT_KEYS = join(ROOT, 'src/data/family-keys.json');
const checkOnly = process.argv.includes('--check');

// The hero's selections (docs/specs/hero.md section 3). Each entry is [id, expected name]; the generator fails if the
// data no longer agrees, so a renamed or re-coloured shade can never slip into the scene silently.
const REGION = [ // one shade per family, in catalog family order (prototype REGION)
  ['frosty-whites-07', 'Snow'], ['blissful-blues-08', 'Sky'], ['playful-pinks-14', 'Rouge'], ['vivid-violets-07', 'Amethyst'],
  ['mellow-yellows-01', 'Sunbeam'], ['earthy-browns-07', 'Cinnamon'], ['blushing-corals-04', 'Mango'], ['stormy-greys-05', 'Silver'],
  ['go-green-12', 'Lawn'], ['roaring-reds-07', 'Crimson'],
];
// block glows, the 'cool' order, by block index 0 to 9 (prototype BLOCK_ORDERS.cool)
const BLOCK_COOL = ['Mango', 'Silver', 'Snow', 'Sky', 'Cinnamon', 'Amethyst', 'Sunbeam', 'Rouge', 'Lawn', 'Crimson'];
// sky galaxy wash, uC1 to uC4 (prototype line 570)
const GALAXY = [['blissful-blues-23', 'Space'], ['vivid-violets-24', 'Eggplant'], ['go-green-22', 'Forest'], ['roaring-reds-23', 'Wine']];
// logotype glitch: pairs (the first is the intro pair) and lightness weights (prototype lines 1180 to 1181)
const GLITCH_PAIRS = [['Sky', 'Crimson'], ['Amethyst', 'Sunbeam'], ['Lawn', 'Rouge'], ['Sky', 'Mango']];
const GLITCH_LIGHT = { Sky: 0.74, Mango: 0.78, Amethyst: 0.56, Sunbeam: 0.94, Crimson: 0.54, Lawn: 0.64, Rouge: 0.69 };

const fail = (msg) => { console.error('gen-shades: ' + msg); process.exit(1); };
const data = JSON.parse(readFileSync(SRC, 'utf8'));
const fams = data.families;
if (!Array.isArray(fams) || fams.length !== 10) fail('expected 10 families');
const all = [];
fams.forEach((f, fi) => {
  if (!/^[a-z]+(-[a-z]+)*$/.test(f.id)) fail(`family id is not URL-safe: ${f.id}`);
  if (f.shades.length !== 24) fail(`${f.id} has ${f.shades.length} shades, not 24`);
  const names = new Set();
  f.shades.forEach((s, si) => {
    if (s.index !== si + 1) fail(`${s.id} is out of order`);
    if (s.id !== `${f.id}-${String(si + 1).padStart(2, '0')}`) fail(`unexpected id ${s.id}`);
    if (!/^#[0-9a-fA-F]{6}$/.test(s.hex)) fail(`${s.id} hex is not #rrggbb: ${s.hex}`);
    if (names.has(s.name)) fail(`${s.name} repeats inside ${f.id}`);
    names.add(s.name);
    all.push({ id: s.id, family: f.id, index: s.index, n: fi * 24 + s.index, name: s.name, hex: s.hex });
  });
});
if (all.length !== 240) fail('expected 240 shades');
const byId = new Map(all.map((s) => [s.id, s]));
const pick = ([id, name]) => {
  const s = byId.get(id);
  if (!s) fail(`no shade with id ${id}`);
  if (s.name !== name) fail(`${id} is ${s.name}, expected ${name}`);
  return { id: s.id, name: s.name, hex: s.hex };
};
const region = REGION.map(pick);
const regionByName = new Map(region.map((s, i) => [s.name, i]));
const blockOrder = BLOCK_COOL.map((n) => { const k = regionByName.get(n); if (k === undefined) fail(`block shade ${n} is not in REGION`); return k; });
const galaxy = GALAXY.map(pick);
const idOf = (name) => { const k = regionByName.get(name); if (k === undefined) fail(`glitch shade ${name} is not in REGION`); return region[k].id; };
const glitchPairs = GLITCH_PAIRS.map(([a, b]) => [idOf(a), idOf(b)]);
const glitchLight = Object.fromEntries(Object.entries(GLITCH_LIGHT).map(([n, v]) => [idOf(n), v]));

const css = ':root{' + all.map((s) => `--shade-${s.id}:${s.hex};`).join('') + '}';

const j = (v) => JSON.stringify(v);
const ts = `// Generated by scripts/hero/gen-shades.mjs from docs/data/shades-240.json. Do not edit by hand.
// Shades are keyed by id: names repeat across families.

export interface Shade { readonly id: string; readonly family: string; readonly index: number; readonly n: number; readonly name: string; readonly hex: string }
export interface ShadeRef { readonly id: string; readonly name: string; readonly hex: string }

/** All 240 shades in catalog order. n is the catalog number, 1 to 240: (family ordinal - 1) x 24 + index. */
export const SHADES: readonly Shade[] = ${j(all)};

/** The 240 hexes in catalog order, frosty-whites-01 to roaring-reds-24 (section 2's interim swatch field). */
export const SHADE_HEX: readonly string[] = ${j(all.map((s) => s.hex))};

/** One key shade per family, in catalog family order (the prototype's REGION). */
export const REGION: readonly ShadeRef[] = ${j(region)};

/** Block glows, the 'cool' order: for block i, REGION[BLOCK_ORDER[i]]. */
export const BLOCK_ORDER: readonly number[] = ${j(blockOrder)};

/** Block glows by block index 0 to 9. */
export const BLOCK_SHADES: readonly ShadeRef[] = ${j(blockOrder.map((k) => region[k]))};

/** The sky's galaxy wash, uC1 to uC4. */
export const GALAXY: readonly ShadeRef[] = ${j(galaxy)};

/** Logotype glitch pairs by id; the first is the intro pair. */
export const GLITCH_PAIRS: readonly (readonly [string, string])[] = ${j(glitchPairs)};

/** Lightness weights for the glitch ghosts, by id. */
export const GLITCH_LIGHT: Readonly<Record<string, number>> = ${j(glitchLight)};
`;

const keys = region.map((s, i) => {
  const sh = byId.get(s.id);
  return { family: fams[i].id, familyName: fams[i].name, shade: s.id, name: s.name, hex: s.hex, index: sh.index, n: sh.n };
});
fams.forEach((f, i) => { if (keys[i].shade.slice(0, f.id.length + 1) !== f.id + '-') fail(`REGION[${i}] is not in ${f.id}`); });
const keysJson = JSON.stringify(keys, null, 2) + '\n';

let stale = false;
for (const [path, text] of [[OUT_CSS, css], [OUT_TS, ts], [OUT_KEYS, keysJson]]) {
  const cur = existsSync(path) ? readFileSync(path, 'utf8') : null;
  if (cur === text) continue;
  if (checkOnly) { console.error(`gen-shades: ${path} is out of date`); stale = true; continue; }
  mkdirSync(dirname(path), { recursive: true });
  writeFileSync(path, text);
}
if (stale) process.exit(1);
console.log(`gen-shades: 240 shades; css ${Buffer.byteLength(css)} B; ts ${Buffer.byteLength(ts)} B; family keys ${keys.length}`);
