// Generated by scripts/hero/gen-glsl.mjs from prototype v9.10 (tests/fixtures/hero-v9.10/template.html; the sky dome, the ground patches, the wind bake and the fog cards). Do not edit by hand:
// tests/unit/glsl.test.ts checks every default string against the prototype. Slots are empty by default.

/** Insertion points on the sky for the v10 intro (uFlat, uSkyP, uSkyB; architecture 11.1). */
export interface SkySlots { fragPars?: string; fragOut?: string }

export const SKY_VERT = 'varying vec2 vUv; varying vec3 vDir; void main(){ vUv = uv; vec4 w = modelMatrix * vec4(position, 1.0); vDir = normalize(w.xyz - cameraPosition); gl_Position = projectionMatrix * viewMatrix * w; }';

export const skyFrag = (s: SkySlots = {}): string => `
      uniform sampler2D tSky; uniform float uSkyGain, uHue, uHueScale; uniform vec3 uC1, uC2, uC3, uC4;
      varying vec2 vUv; varying vec3 vDir;${s.fragPars ?? ''}
      float h31(vec3 p){ p = fract(p * 0.3183099 + 0.1); p *= 17.0; return fract(p.x * p.y * p.z * (p.x + p.y + p.z)); }
      float n3(vec3 x){ vec3 i = floor(x), f = fract(x); f = f * f * (3.0 - 2.0 * f);
        return mix(mix(mix(h31(i), h31(i + vec3(1,0,0)), f.x), mix(h31(i + vec3(0,1,0)), h31(i + vec3(1,1,0)), f.x), f.y),
                   mix(mix(h31(i + vec3(0,0,1)), h31(i + vec3(1,0,1)), f.x), mix(h31(i + vec3(0,1,1)), h31(i + vec3(1,1,1)), f.x), f.y), f.z); }
      float fbm(vec3 p){ float a = 0.0, w = 0.5; for (int i = 0; i < 5; i++) { a += w * n3(p); p = p * 2.03 + 11.7; w *= 0.5; } return a; }
      void main(){
        vec3 sky = texture2D(tSky, vUv).rgb * uSkyGain;
        vec3 d = vDir * uHueScale;
        float a = fbm(d + 3.1), b = fbm(d * 1.3 - 7.4), c = fbm(d * 0.8 + 19.0), e = fbm(d * 1.7 + 41.0);
        vec3 wash = uC1 * smoothstep(0.38, 0.78, a) + uC2 * smoothstep(0.42, 0.8, b) + uC3 * smoothstep(0.48, 0.84, c) + uC4 * smoothstep(0.5, 0.86, e);
        wash *= smoothstep(-0.03, 0.12, vDir.y);                       // nothing at the horizon line itself
        float dark = 1.0 - smoothstep(0.02, 0.18, dot(sky, vec3(0.2126, 0.7152, 0.0722)));
        gl_FragColor = vec4(sky + wash * uHue * dark, 1.0);${s.fragOut ?? ''}
      }`;

/** The ground's onBeforeCompile replacements: '#include <common>' and '#include <project_vertex>' in the vertex shader. */
export const GROUND_VERT_COMMON = '#include <common>\nvarying vec3 vWPos;';
export const GROUND_VERT_PROJECT = '#include <project_vertex>\nvWPos = (modelMatrix * vec4(transformed, 1.0)).xyz;';
/** The ground's fragment replacements: '#include <common>' (tone, crumb and mist declarations) and '#include <map_fragment>'. */
export const GROUND_FRAG_COMMON = `#include <common>
      varying vec3 vWPos; uniform float uCrumb, uCrumbSize, uGExp, uGGamma, uGNear, uGToe;
      #define vGroundW vWPos
uniform sampler2D tWindProc;
uniform float uTime;
uniform float uGMAmount;   // 0.55 ground mist strength (0 = off)
uniform float uGMScale;    // 0.1  repeats per world unit (igloo terrain 0.1, second tap x1.5)
uniform float uGMVelX;     // 0.25 repeats per second along x (igloo 0.25)
uniform float uGMVelZ;     // 0.3  repeats per second along z (igloo 0.3)
uniform float uGMNear;     // 6.0  streaks start this far from the camera (full at 2x)
uniform float uGMFar;      // 140.0 streaks gone by here (start fading at half)
uniform float uGMLitOnly;  // 0.6  follow the baked light (igloo multiplies by colour.r)
uniform vec3  uFogColor;
uniform float uFogBright;

float gtap(vec2 p) { return pow(texture2D(tWindProc, p).r, 2.2); }
      float gh(vec2 p){ p = fract(p * vec2(123.34, 456.21)); p += dot(p, p + 45.32); return fract(p.x * p.y); }
      float gn(vec2 p){ vec2 i = floor(p), f = fract(p); f = f * f * (3.0 - 2.0 * f);
        return mix(mix(gh(i), gh(i + vec2(1, 0)), f.x), mix(gh(i + vec2(0, 1)), gh(i + vec2(1, 1)), f.x), f.y); }
      float billow(vec2 p){ float a = 0.0, w = 0.55; for (int i = 0; i < 4; i++) { a += w * gn(p); p = p * 2.07 + 5.3; w *= 0.5; } return a; }`;
export const GROUND_FRAG_MAP = `#include <map_fragment>
      {
        float dist = length(vWPos - cameraPosition);
        // tone: the bake is fitted to igloo's floor in Blender, but the lit faces come through a stop too bright on the
        // page; a soft power curve in linear light (measured against igloo's hero shot, band by band) brings every lit
        // band to igloo's level while the shaded flanks stay put. Then igloo's foreground is darker than its mid field,
        // ours was the reverse: a gentle falloff toward the camera (full by 20 units) matches that and keeps the headline legible.
        diffuseColor.rgb = uGExp * pow(max(diffuseColor.rgb, 0.0), vec3(uGGamma));
        diffuseColor.rgb *= mix(uGNear, 1.0, smoothstep(6.0, 20.0, dist));
        // soft toe in linear light: 0 maps to uGToe, values well above it are untouched (shaded snow, never a hole)
        diffuseColor.rgb = 0.5 * (diffuseColor.rgb + sqrt(diffuseColor.rgb * diffuseColor.rgb + 4.0 * uGToe * uGToe));
        vec2 q = vWPos.xz / max(uCrumbSize, 0.005);
        float crumb = gn(q) * 0.5 + gn(q * 2.3 + 7.1) * 0.3 + gh(floor(q * 3.1)) * 0.2 - 0.5;
        diffuseColor.rgb *= 1.0 + crumb * uCrumb * (1.0 - smoothstep(6.0, 45.0, dist));
      }
{
  vec2 gp = vec2(2.0 * vGroundW.x, vGroundW.z + vGroundW.y) * uGMScale;   // igloo's xz + xy mapping
  float gw = gtap(gp + vec2(-uTime * uGMVelX, -uTime * uGMVelZ))
           * gtap(gp * 1.5 + vec2(-uTime * uGMVelX * 0.72, -uTime * uGMVelZ * 0.75));
  float d = distance(cameraPosition.xz, vGroundW.xz);
  float band = smoothstep(uGMNear, 2.0 * uGMNear, d) * (1.0 - smoothstep(0.5 * uGMFar, uGMFar, d));
  float lum = dot(diffuseColor.rgb, vec3(0.2126, 0.7152, 0.0722));
  float lit = mix(1.0, clamp(lum * 6.0, 0.0, 1.0), uGMLitOnly);
  diffuseColor.rgb += uFogColor * uFogBright * gw * 2.0 * band * lit * uGMAmount;
}
      {
      }`;

export const WIND_VERT = `varying vec2 vUv;
void main() { vUv = uv; gl_Position = vec4(position.xy, 0.0, 1.0); }`;
export const WIND_FRAG = `precision highp float;
varying vec2 vUv;
uniform vec2  uPeriod;     // lattice cells across the tile, (3, 5): matches the reference tile's 28 x 20 px correlation
uniform float uWarp;       // domain warp, 0.6
uniform float uEmboss;     // relief shading of the noise heightfield, 0.3 (the wind-swept billow look)
uniform float uHeightMix;  // 0 = relief only, 1 = height only, 0.6
uniform float uOctGain;    // fbm gain, 0.45
uniform float uSeed;       // any value, reseeds the tile
uniform vec2  uNorm;       // (scale, bias) onto mean 0.475, sd 0.116: (1.338, -0.176)

float hash21(vec2 c) { return fract(sin(dot(c + uSeed, vec2(127.1, 311.7))) * 43758.5453); }
float vnoiseP(vec2 p, vec2 P) {                       // periodic value noise, so the tile repeats seamlessly
  vec2 i = floor(p), f = fract(p), u = f * f * (3.0 - 2.0 * f);
  vec2 i0 = mod(i, P), i1 = mod(i + 1.0, P);
  return mix(mix(hash21(i0), hash21(vec2(i1.x, i0.y)), u.x),
             mix(hash21(vec2(i0.x, i1.y)), hash21(i1), u.x), u.y);
}
float fbmP(vec2 p, vec2 P, int oct, float gain) {
  float s = 0.0, a = 0.5, n = 0.0;
  for (int i = 0; i < 5; i++) {
    if (i >= oct) break;
    s += a * vnoiseP(p, P); n += a;
    p = p * 2.0 + vec2(0.37, 0.71); P *= 2.0; a *= gain;   // offset keeps the period, breaks lattice alignment (no straight seams)
  }
  return s / n;
}
float heightP(vec2 uv) {
  vec2 p = uv * uPeriod;
  float qx = fbmP(p, uPeriod, 3, 0.5);
  float qy = fbmP(p + uPeriod * vec2(0.37, 0.61), uPeriod, 3, 0.5);
  return fbmP(p + uWarp * vec2(2.0 * (qx - 0.5), qy - 0.5), uPeriod, 4, uOctGain);   // warp mostly along x
}
void main() {
  const float N = 256.0;
  vec2 ex = vec2(1.0 / N, 0.0), ey = vec2(0.0, 1.0 / N);
  float h  = heightP(vUv);
  float hu = (heightP(vUv + ex) - heightP(vUv - ex)) * (0.5 * N) / uPeriod.x;
  float hv = (heightP(vUv + ey) - heightP(vUv - ey)) * (0.5 * N) / uPeriod.y;
  float shade = 0.5 + uEmboss * (0.8 * hu + 0.6 * hv);
  float n = mix(shade, h, uHeightMix);
  gl_FragColor = vec4(vec3(clamp(n * uNorm.x + uNorm.y, 0.13, 0.80)), 1.0);   // the reference tile's range
}`;

export const FOG_VERT = `varying vec2  vUv;
varying vec2  vLocal;
varying vec3  vWorld;
varying vec3  vNormalW;
varying float vViewDepth;
void main() {
  vUv = uv;
  vLocal = position.xy;                                      // card-local, world units (mesh unscaled)
  vec4 w = modelMatrix * vec4(position, 1.0);
  vWorld = w.xyz;
  vNormalW = normalize(mat3(modelMatrix) * vec3(0.0, 0.0, 1.0));
  vec4 mv = viewMatrix * w;
  vViewDepth = -mv.z;
  gl_Position = projectionMatrix * mv;
}`;
export const FOG_FRAG = `uniform sampler2D tWindProc;
uniform float uTime;
uniform vec2  uTile;       // per card: world units per noise repeat (x, y)
uniform float uPhase;      // per card: seconds added to this card's clock (igloo 0.0 and 0.914)
uniform float uFront;      // per card: 1 if between camera and logo (logo guard applies)
uniform float uTileMul;    // 1.0  wisp size
uniform float uSpeed;      // 0.15 repeats per second (igloo)
uniform float uRise;       // 1.0  scales igloo's vertical drifts +0.4 and -0.35
uniform float uGain;       // 8.0  gain on the three-tap product (igloo)
uniform float uHaze;       // 0.03 flat density under the wisps (igloo 0)
uniform float uDensity;    // 1.0  fog amount
uniform float uMaxAlpha;   // 0.45 ceiling per card
uniform float uOpacity;    // 1.0  intro fade
uniform float uEdgeX;      // 0.2  side fade, fraction of width
uniform float uBottomRamp; // 0.1  fade-in from the bottom edge (igloo 0.1)
uniform float uTopFade;    // 1.6  exponent on (1 - v); igloo 1.0, higher hugs the ground
uniform float uSoftDepth;  // 3.0  depth softness per 10 units of distance (SOFT_DEPTH)
uniform float uNearStart;  // 6.0
uniform float uNearEnd;    // 12.0
uniform float uFarStart;   // 220.0
uniform float uFarEnd;     // 420.0 (scene fog far is 430)
uniform float uGrazing;    // 0.25 fade when a card is seen edge-on
uniform vec3  uFogColor;   // Pearl Whisper #F7F6F3 in linear: (0.930, 0.923, 0.896)
uniform float uFogBright;  // 0.22
uniform float uLift;       // 0.35 thicker wisps glow a little (moonlit core)
uniform vec4  uLogoRect;   // logo on screen: uv centre (x, y), uv half-size (x, y)
uniform float uLogoClear;  // 0.8  fraction of fog removed over the logo
uniform float uLogoSoft;   // 0.35 guard edge softness
uniform vec2  uResolution; // drawing-buffer px of the target being drawn
#ifdef SOFT_DEPTH
uniform sampler2D tDepth;  // hero DepthTexture, same framing
uniform float uCamNear;
uniform float uCamFar;
float linDepth(float d) { float z = d * 2.0 - 1.0; return 2.0 * uCamNear * uCamFar / (uCamFar + uCamNear - z * (uCamFar - uCamNear)); }
#endif
varying vec2  vUv;
varying vec2  vLocal;
varying vec3  vWorld;
varying vec3  vNormalW;
varying float vViewDepth;

float tap(vec2 p) { return pow(texture2D(tWindProc, p).r, 2.2); }   // sRGB-like decode: keeps the product sparse
float ign(vec2 p) { return fract(52.9829189 * fract(dot(p, vec2(0.06711056, 0.00583715)))); }

void main() {
  vec2 uv = vLocal / (uTile * uTileMul);
  float t = (uTime + uPhase) * uSpeed;
  float w = tap(uv + vec2(-t, 0.4 * uRise * t))            // three scales, all drifting +x at different
          * tap(uv * 1.25 + vec2(-t, 0.75))                 // world speeds; one rises, one sinks, so the
          * tap(uv * 0.5 + vec2(-t, -0.35 * uRise * t));    // product boils instead of sliding
  w *= uGain;

  float a = uHaze + w;
  a *= pow(1.0 - vUv.y, uTopFade) * smoothstep(0.0, uBottomRamp, vUv.y);
  a *= smoothstep(0.0, uEdgeX, vUv.x) * smoothstep(1.0, 1.0 - uEdgeX, vUv.x);
  a *= smoothstep(uNearStart, uNearEnd, vViewDepth) * (1.0 - smoothstep(uFarStart, uFarEnd, vViewDepth));
  a *= smoothstep(0.0, uGrazing, abs(dot(normalize(cameraPosition - vWorld), normalize(vNormalW))));

  vec2 suv = gl_FragCoord.xy / uResolution;
#ifdef SOFT_DEPTH
  float soft = uSoftDepth * max(1.0, vViewDepth * 0.1);     // softness grows with distance: no seam when the camera looks down
  a *= clamp((linDepth(texture2D(tDepth, suv).r) - vViewDepth) / soft, 0.0, 1.0);   // occlusion + soft ground contact
#endif
  vec2 q = (suv - uLogoRect.xy) / max(uLogoRect.zw, vec2(1e-4));
  a *= 1.0 - uLogoClear * uFront * (1.0 - smoothstep(1.0 - uLogoSoft, 1.0 + uLogoSoft, length(q)));

  a = min(a * uDensity, uMaxAlpha) * uOpacity;
  a += (ign(gl_FragCoord.xy) - 0.5) / 255.0;                // dither against banding on the near-black floor
  vec3 col = uFogColor * uFogBright * (1.0 + uLift * clamp(w, 0.0, 1.0));
  gl_FragColor = vec4(col, clamp(a, 0.0, 1.0));
  #include <colorspace_fragment>
}`;
