// Every string on the family pages (docs/specs/family-page.md section 3). Pure functions of the data, shared by the
// Astro components (build) and the page module (runtime), so the HTML and the live updates can never disagree.
// No em dashes, no emojis, sentence case (CLAUDE.md rules 3, 16, 29).

export interface CopyShade { readonly name: string; readonly index: number; readonly n: number; readonly nnn: string }

export const FAM_COPY = {
  title: (family: string) => `${family}, all 24 shades. Skreed`,
  description: (family: string, first: string, last: string) => `All 24 ${family} shades, from ${first} to ${last}, on a Skreed case in matte or gloss. Doors open Nov 1.`,
  home: 'Skreed home',
  families: 'Families',
  eyebrow: (ordinal2: string) => `${ordinal2} / 10 Families`,
  stage: (family: string, shade: string) => `24 ${family} cases in a row. ${shade} is in front.`,
  prev: 'Previous shade',
  next: 'Next shade',
  number: (s: CopyShade) => `${s.nnn} / 240`,
  numberSr: (s: CopyShade) => `Shade ${s.n} of 240`,
  scrubber: 'Shade',
  scrubberText: (s: CopyShade) => `${s.name}, ${s.index} of 24`,
  finish: 'Finish',
  matte: 'Matte',
  gloss: 'Gloss',
  reserve: 'Reserve my shade',
  reserveAria: (shade: string) => `Reserve my shade, ${shade}`,
  reserveHref: (s: CopyShade, finish: 'matte' | 'gloss') => `/?shade=${s.nnn}&finish=${finish}#reserve`,
  h2: 'The whole family.',
  gridGroup: (family: string) => `${family}, 24 shades`,
  swatch: (s: CopyShade, family: string) => `${s.name}, ${family}, ${s.index} of 24`,
  caption: (s: CopyShade, family: string) => `${s.name}, ${family}`,
  prevFamily: 'Previous family',
  nextFamily: 'Next family',
  allShades: 'All 240 shades',
  allShadesHref: (slug: string) => `/?family=${slug}#wall`,
  switcherClose: 'Close',
  live: (s: CopyShade, family: string) => `${s.name}. ${family}. Shade ${s.n} of 240.`,
  modelFailed: 'Could not load the 3D cases. Showing the swatches.',
  modelFailedTwice: 'Could not load the 3D cases. Reload the page to try again.',
  offline: 'You are offline. Showing the swatches.',
  slow: 'Still loading the 3D cases.',
  saveData: 'Data saver is on. Showing the swatches.',
  slowConnection: 'Slow connection. Showing the swatches.',
  show3d: (mb: string) => `Show in 3D, ${mb} MB`,
  tryAgain: 'Try again',
  reload: 'Reload',
  familyLink: (family: string) => `${family}, all 24 shades`,
  // interim footer facts (CHECKLIST G19, G24) until the landing's footer (section 8) exists
  email: 'collab@skreed.in',
  place: 'Hyderabad, Telangana',
  reply: 'We reply on WhatsApp within one working day.',
  instagram: '@skreedofficial',
  instagramHref: 'https://www.instagram.com/skreedofficial/',
} as const;
