// Generated by scripts/hero/gen-glsl.mjs from prototype v9.10 (tests/fixtures/hero-v9.10/template.html; the logo material). Do not edit by hand:
// tests/unit/glsl.test.ts checks every default string against the prototype. Slots are empty by default.

/** Insertion points for the v10 intro and section 2's logo morph (architecture 11.1, 11.2). */
export interface LogoSlots { vertPars?: string; vertPos?: string; fragPars?: string; fragOut?: string }

export const logoVert = (MAXB: number, s: LogoSlots = {}): string => `
    #define NB ${MAXB}
    uniform vec3 uOff[NB]; uniform vec4 uQ[NB]; uniform float uD[NB]; uniform float uRelief;
    attribute float aId; attribute vec3 aCentroid; attribute float aSide; attribute float aH; attribute float aEdge;
    varying vec3 vW; varying vec3 vRest; varying float vSide; varying float vDisp; varying float vId; varying vec2 vCen; varying float vEdge;${s.vertPars ?? ''}
    vec3 qrot(vec4 q, vec3 v){ return v + 2.0 * cross(q.xyz, cross(q.xyz, v) + q.w * v); }
    void main(){
      int i = int(aId + 0.5);
      vec3 pos = position; pos.z += aH * uRelief;                 // the chiselled relief
      vec3 local = (pos - aCentroid) * 0.992;                     // a hair of seam between blocks
      vec3 p = aCentroid + uOff[i] + qrot(uQ[i], local);${s.vertPos ?? ''}
      vec4 wp = modelMatrix * vec4(p, 1.0);
      vW = wp.xyz; vRest = pos; vSide = aSide; vDisp = uD[i]; vId = aId; vCen = aCentroid.xy; vEdge = aEdge;
      gl_Position = projectionMatrix * viewMatrix * wp;
    }`;

export const logoFrag = (MAXB: number, s: LogoSlots = {}): string => `
    uniform vec3 uBlockCol[${MAXB}];
    uniform float uTime, uGlow, uRest, uTint, uGrad, uTex, uKey, uRim, uSpec, uRough, uBounce, uAmb; uniform vec3 uRimDir;
    uniform float uBevelW, uBevelAng, uAlb, uWrap, uKeyRad, uRimRad, uRim2, uRim2Rad, uFloor, uHz, uSky, uKTemp, uWear, uOcc, uKnee; uniform vec3 uKeyPos, uRimPos, uRim2Pos;
    varying vec3 vW; varying vec3 vRest; varying float vSide; varying float vDisp; varying float vId; varying vec2 vCen; varying float vEdge;${s.fragPars ?? ''}
    float h21(vec2 p){ p = fract(p * vec2(123.34, 456.21)); p += dot(p, p + 45.32); return fract(p.x * p.y); }
    float vnoise(vec2 p){ vec2 i = floor(p), f = fract(p); f = f * f * (3.0 - 2.0 * f);
      return mix(mix(h21(i), h21(i + vec2(1, 0)), f.x), mix(h21(i + vec2(0, 1)), h21(i + vec2(1, 1)), f.x), f.y); }

    #define PI 3.14159265
    // GGX / Trowbridge-Reitz (Walter 2007), Schlick Fresnel (1994), Schlick-GGX Smith visibility (Karis 2013)
    float D_GGX(float NH, float a2){ float d = NH * NH * (a2 - 1.0) + 1.0; return a2 / (PI * d * d); }
    float G_Smith(float NV, float NL, float alpha){ float k = alpha * 0.5; return (NV / (NV * (1.0 - k) + k)) * (NL / (NL * (1.0 - k) + k)); }
    float F_Schlick(float VH, float F0){ return F0 + (1.0 - F0) * pow(1.0 - VH, 5.0); }
    // sphere area light (Karis 2013, representative point): the point on the sphere nearest the reflection ray stands in
    // for the whole source, and the lobe is widened by the source's angular size so a big soft source does not blow out.
    // Returns the specular term (already times NL); NLc is the plain cosine to the sphere's centre for the diffuse.
    float sphereSpec(vec3 Pl, float rad, vec3 Pw, vec3 N, vec3 V, float rough, float F0, out float NLc){
      vec3 Lc = Pl - Pw; float dist = length(Lc); NLc = dot(N, Lc / dist);
      vec3 R = reflect(-V, N); vec3 toRay = dot(Lc, R) * R - Lc;
      vec3 L = normalize(Lc + toRay * clamp(rad / max(length(toRay), 1e-4), 0.0, 1.0));
      float alpha = rough * rough, a2 = alpha * alpha;
      float alphaW = clamp(alpha + rad / (2.0 * dist), 0.0, 1.0); float norm = alpha / alphaW; norm *= norm;
      vec3 H = normalize(L + V);
      float NL = max(dot(N, L), 0.0), NV = max(dot(N, V), 1e-3), NH = max(dot(N, H), 0.0), VH = max(dot(V, H), 0.0);
      return D_GGX(NH, a2) * F_Schlick(VH, F0) * G_Smith(NV, NL, alpha) / max(4.0 * NV * NL, 1e-3) * NL * norm;
    }
    void main(){
      vec3 V = normalize(cameraPosition - vW);
      vec3 N = normalize(cross(dFdx(vW), dFdy(vW)));            // true facet normal from the geometry itself
      if (dot(N, V) < 0.0) N = -N;
      vec2 tp = vSide < 0.5 ? vRest.xy : vec2(vRest.x + vRest.y, vRest.z * 1.7);
      float grain = vnoise(tp * 90.0) * 0.6 + vnoise(tp * 31.0) * 0.4;
      float mottle = vnoise(tp * 1.3 + 7.0);
      // one colour per block, with a gradient inside it: the same shade runs from deeper at the block's inner edge
      // to brighter at its outer edge (radial from the logo's centre), so no block ever carries two families
      vec3 shade = uBlockCol[int(vId + 0.5)];
      vec2 rdir = normalize(vCen + vec2(1e-4));
      float g = clamp(0.5 + dot(vRest.xy - vCen, rdir) / 1.4, 0.0, 1.0);
      shade *= mix(1.0 - 0.55 * uGrad, 1.0 + 0.35 * uGrad, g);
      // ---- material: matte black. Black paint sits at 2 to 5% diffuse albedo; a dielectric has F0 = 0.04, so on a black
      // surface the specular sheen carries more light than the diffuse: black is lit by what it reflects.
      float albedo = uAlb * mix(1.0, (0.8 + 0.4 * grain) * (0.85 + 0.3 * mottle), uTex);
      vec3 base = vSide > 0.5 ? mix(vec3(albedo), shade * albedo * 2.2, uTint * 6.0) : vec3(albedo);
      const float F0 = 0.04;
      // ---- bevel: within uBevelW of the block outline tilt the normal outward (normal-only round corner, as Arnold's
      // round_corners and Blender's Bevel node do), so the edge has a surface for the kicker and the floor to land on
      vec3 Nf = N; float bev = 0.0;
      if (vSide < 0.5) {
        float fw = fwidth(vEdge) * 0.75;
        float t = 1.0 - smoothstep(uBevelW - fw, uBevelW + fw, vEdge);
        if (t > 0.0) {
          vec2 de = vec2(dFdx(vEdge), dFdy(vEdge));
          vec3 dWx = dFdx(vW), dWy = dFdy(vW);
          float a = dot(dWx, dWx), b = dot(dWx, dWy), c = dot(dWy, dWy); float det = max(a * c - b * b, 1e-14);
          vec3 inward = ((c * de.x - b * de.y) * dWx + (a * de.y - b * de.x) * dWy) / det;
          if (dot(inward, inward) < 1e-10) inward = vec3(vCen - vRest.xy, 0.0);     // a boundary-only triangle: fall back to the block centre
          bev = t; float ang = t * uBevelAng;
          Nf = normalize(N * cos(ang) - normalize(inward) * sin(ang));
        }
      }
      float NV = max(dot(Nf, V), 1e-3);
      // roughness: the grain breaks the sheen like real matte paint; a handled edge is a touch glossier (edge wear)
      float rough = clamp(uRough * (0.9 + 0.2 * grain), 0.2, 1.0); rough = mix(rough, 0.35, uWear * bev * mottle);
      // ---- key: one big soft source, front upper left (the moon behind the camera, the same light that lights the snow).
      // Lambert with a soft wrap for the body, plus the broad GGX sheen: on matte black the sheen is the gradient you see.
      float NLk; float specK = sphereSpec(uKeyPos, uKeyRad, vW, Nf, V, rough, F0, NLk);
      float dK = length(uKeyPos - vW); float keyI = uKey * 100.0 / (dK * dK);         // inverse square, 1.0 at 10 units
      float diffK = max((NLk + uWrap) / (1.0 + uWrap), 0.0);
      vec3 keyCol = uKTemp >= 0.0 ? mix(vec3(1.0), vec3(1.0, 0.96, 0.90), uKTemp) : mix(vec3(1.0), vec3(0.84, 0.90, 1.0), -uKTemp);
      vec3 col = base * keyCol * keyI * diffK + uSpec * keyCol * keyI * specK;
      // ---- kicker: a cool strip source behind and above, on the side where the sky is blackest. It lands on the bevel
      // ring and the side faces only: that line is the silhouette.
      vec3 rimCol = vec3(0.80, 0.88, 1.0);
      float NLr; float specR = sphereSpec(uRimPos, uRimRad, vW, Nf, V, max(rough * 0.8, 0.25), F0, NLr);
      float dR = length(uRimPos - vW); float rimI = uRim * 100.0 / (dR * dR);
      col += rimCol * rimI * (specR + base * max(NLr, 0.0) * 0.5);
      if (uRim2 > 0.0) {   // second, weaker strip on the other side (optional)
        float NLr2; float specR2 = sphereSpec(uRim2Pos, uRim2Rad, vW, Nf, V, max(rough * 0.8, 0.25), F0, NLr2);
        float dR2 = length(uRim2Pos - vW); float rimI2 = uRim2 * 100.0 / (dR2 * dR2);
        col += rimCol * rimI2 * (specR2 + base * max(NLr2, 0.0) * 0.5);
      }
      // ---- environment: the snow floor below (bright, cool white), a fog band at the horizon, the near-black violet sky
      // above. Specular with roughness-aware Fresnel: the floor reflects in the under faces and the lower bevels at
      // grazing angles (that is the floor bounce you can actually see on a black object); diffuse hemisphere for the rest.
      vec3 R = reflect(-V, Nf);
      vec3 envFloor = vec3(0.86, 0.90, 1.0) * uFloor, envHz = vec3(0.92, 0.93, 1.0) * uHz, envSky = vec3(0.60, 0.45, 0.90) * uSky;
      vec3 env = mix(envFloor, envHz, smoothstep(-0.35, -0.02, R.y)); env = mix(env, envSky, smoothstep(0.0, 0.30, R.y));
      float Fr = F0 + (max(1.0 - rough, F0) - F0) * pow(1.0 - NV, 5.0);
      col += uBounce * env * Fr;
      col += uAmb * base * mix(envFloor, envSky, 0.5 + 0.5 * Nf.y);
      // the cut faces inside the S see less of the rig; a knee keeps the black material under the bloom threshold (0.62)
      col *= 1.0 - uOcc * vSide * (0.4 + 0.6 * smoothstep(0.5, -0.5, vRest.z));
      float hi = max(col.r, max(col.g, col.b)); if (hi > uKnee) col *= (uKnee + (hi - uKnee) * 0.3) / hi;
      // inner glow: the cut faces carry the shade, brighter as the block lifts away (igloo mixes by 5 x displacement)
      float lift = clamp(5.0 * vDisp, 0.0, 1.0);
      float deep = vSide * (0.55 + 0.45 * smoothstep(0.5, -0.5, vRest.z));
      float shimmer = 0.85 + 0.15 * sin(uTime * 1.3 + vRest.x * 2.1 + vRest.y * 1.7);
      col += shade * deep * (uRest + uGlow * lift) * shimmer;
      // alpha marks the black faces (0) so the bloom pass can keep its haze off them
      gl_FragColor = vec4(col, vSide > 0.5 ? 1.0 : 0.0);${s.fragOut ?? ''}
    }`;
