// Generated by scripts/hero/gen-glsl.mjs from prototypes/hero-v9/template.html (the bloom restore pass and the wipe composite). Do not edit by hand:
// tests/unit/glsl.test.ts checks every default string against the prototype. Slots are empty by default.

/** Insertion points on the composite for the v10 intro (uIntro) and section 2's rock modes (architecture 11.1, 11.2). */
export interface CompositeSlots { fragPars?: string; fragOut?: string }

export const RESTORE_VERT = 'varying vec2 vUv; void main(){ vUv = uv; gl_Position = projectionMatrix * modelViewMatrix * vec4(position, 1.0); }';
export const RESTORE_FRAG = 'uniform sampler2D tDiffuse, tClean; varying vec2 vUv; void main(){ vec4 c = texture2D(tClean, vUv); vec3 b = texture2D(tDiffuse, vUv).rgb; gl_FragColor = vec4(mix(c.rgb, b, step(0.5, c.a)), 1.0); }';

export const COMPOSITE_VERT = `varying vec2 vUv; void main(){ vUv = uv; gl_Position = vec4(position.xy, 0.0, 1.0); }`;

export const compositeFrag = (s: CompositeSlots = {}): string => `
    uniform sampler2D tA, tB, tScroll; uniform float uProgress, uAspect, uCalm; uniform vec2 uNoiseOff;${s.fragPars ?? ''}
    varying vec2 vUv;
    float linstep(float a, float b, float t){ return clamp((t - a) / (b - a), 0.0, 1.0); }
    // a sweep from start to end with a soft margin; progress 0..1 moves it across
    float falloff(float x, float start, float end, float margin, float progress){
      float m = margin * sign(end - start); float p = mix(start - m, end, progress); return linstep(p + m, p, x); }
    float cubicIn(float t){ return t * t * t; }
    // dither: interleaved gradient noise, re-offset every frame (igloo uses a blue-noise texture)
    float ign(vec2 p){ return fract(52.9829189 * fract(dot(p, vec2(0.06711056, 0.00583715)))); }
    // 5-tap spectral chromatic aberration with a barrel bend
    vec4 spectrum(float t){ float lo = step(t, 0.5); float hi = 1.0 - lo; float w = clamp(1.0 - abs(2.0 * clamp((t - 1.0/6.0) / (4.0/6.0), 0.0, 1.0) - 1.0), 0.0, 1.0);
      return pow(vec4(lo, 1.0, hi, 1.0) * vec4(1.0 - w, w, 1.0 - w, 1.0), vec4(1.0 / 2.2)); }
    vec2 barrel(vec2 uv, float amt){ vec2 cc = uv - 0.5; return uv + cc * dot(cc, cc) * amt; }
    vec3 ca(sampler2D t, vec2 uv, float maxd, float bend){
      vec4 sum = vec4(0.0), sw = vec4(0.0);
      for (int i = 0; i < 5; i++) { float k = float(i) / 5.0; vec4 w = spectrum(k); sw += w; sum += w * texture2D(t, barrel(uv, bend * maxd * k)); }
      return (sum / sw).rgb; }
    void main(){
      if (uProgress <= 0.0) { gl_FragColor = vec4(texture2D(tA, vUv).rgb, 1.0); return; }
      if (uProgress >= 1.0) { gl_FragColor = vec4(texture2D(tB, vUv).rgb, 1.0); return; }
      vec2 uvTex = vUv - 0.5; uvTex.x *= uAspect; uvTex += 0.5;
      vec3 st = texture2D(tScroll, uvTex).rgb;
      float slopeDisp = (st.b * 2.0 - 1.0) * 0.4;
      float slope = -0.2 * uAspect;
      float incl = vUv.x + slopeDisp;
      float incP = uProgress * (1.0 + abs(slope));
      float sweep = vUv.y + incl * abs(slope);
      float blurDiag = falloff(sweep, 0.0, 1.0, 2.0, incP);
      float dispDiag = falloff(sweep, 0.0, 1.0, 0.9, incP);
      float cutDisp = falloff(st.g, 0.0, 1.0, 1.0, dispDiag);
      float cutDiag = falloff(sweep, 0.0, 1.0, 0.2, incP);
      float cut = falloff(st.r, 0.0, 1.0, 2.0, cutDiag);
      float parallaxY = 0.4 * (1.0 - uCalm); float disp = 0.025 * (1.0 - uCalm);
      vec2 n = vec2(ign(gl_FragCoord.xy + uNoiseOff * 97.0), ign(gl_FragCoord.xy + uNoiseOff.yx * 131.0 + 17.0));
      float modulator = 12.0 * (1.0 - uCalm) * smoothstep(1.0, 0.7, abs(vUv.x * 2.0 - 1.0)) * smoothstep(1.0, 0.7, abs(vUv.y * 2.0 - 1.0));
      vec3 s1 = vec3(0.0), s2 = vec3(0.0);
      if (cut < 1.0) s1 = ca(tA, vUv - vec2(0.0, parallaxY * cubicIn(uProgress) + disp * cutDisp), modulator, blurDiag * n.x);
      if (cut > 0.0) s2 = ca(tB, vUv + vec2(0.0, parallaxY * cubicIn(1.0 - uProgress) + disp * (1.0 - cutDisp)), modulator, (1.0 - blurDiag) * n.y);
      gl_FragColor = vec4(clamp(mix(s1, s2, cut), 0.0, 1.0), 1.0);${s.fragOut ?? ''}
    }`;
